version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.3

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2G
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
          path: ~/repo/build/e_final
